// Copyright Epic Games, Inc. All Rights Reserved.

#include "EventsK2Node_NotifyEvent.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "BlueprintNodeSpawner.h"
#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintEventLibrary.h"
#include "EventsManager.h"
#include "EventSystemBPLibrary.h"
#include "K2Node_CallFunction.h"
#include "KismetCompilerMisc.h"
#include "KismetCompiler.h"


UEventsK2Node_NotifyEvent::UEventsK2Node_NotifyEvent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	OrphanedPinSaveMode = ESaveOrphanPinMode::SaveNone;
}

UEdGraphPin* UEventsK2Node_NotifyEvent::CreatePinFromUserDefinition(const TSharedPtr<FUserPinInfo> NewPinInfo)
{
	UEdGraphPin* Pin = CreatePin(EGPD_Input, NewPinInfo->PinType, NewPinInfo->PinName);
	const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();
	K2Schema->SetPinAutogeneratedDefaultValue(Pin,NewPinInfo->PinDefaultValue);
	return Pin;
}

void UEventsK2Node_NotifyEvent::AddInnerPin(FName PinName, const FEdGraphPinType& PinType)
{
	CreateUserDefinedPin(PinName, PinType);
}

void UEventsK2Node_NotifyEvent::ExpandNode(class FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	static const FName FuncName = GET_FUNCTION_NAME_CHECKED(UEventSystemBPLibrary, NotifyEventByKeyVariadic);

	UEventsK2Node_NotifyEvent* SpawnNode = this;
	UEdGraphPin* SpawnEventExec = GetExecPin();
	UEdGraphPin* SpawnMsgPin = GetEventPin();
	UEdGraphPin* SpawnSenderPin = GetSelfPin();
	UEdGraphPin* SpawnNodeThen = GetThenPin();


	UK2Node_CallFunction* CallNotifyFuncNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(SpawnNode, SourceGraph);
	CallNotifyFuncNode->FunctionReference.SetExternalMember(FuncName, UEventSystemBPLibrary::StaticClass());
	CallNotifyFuncNode->AllocateDefaultPins();
	
	bool bError = true;

	UEdGraphPin* CallExecPin = CallNotifyFuncNode->GetExecPin();
	bError &= CompilerContext.MovePinLinksToIntermediate(*SpawnEventExec, *CallExecPin).CanSafeConnect();

	UEdGraphPin* CallMessageIdPin = CallNotifyFuncNode->FindPinChecked(TEXT("MessageId"));
	bError &= CompilerContext.MovePinLinksToIntermediate(*SpawnMsgPin, *CallMessageIdPin).CanSafeConnect();

	UEdGraphPin* CallSenderPin = CallNotifyFuncNode->FindPinChecked(TEXT("Sender"));
	bError &= CompilerContext.MovePinLinksToIntermediate(*SpawnSenderPin, *CallSenderPin).CanSafeConnect();

	UEdGraphPin* CallThen = CallNotifyFuncNode->GetThenPin();
	bError &= CompilerContext.MovePinLinksToIntermediate(*SpawnNodeThen, *CallThen).CanSafeConnect();

	const UEdGraphSchema_K2* K2Schema = CompilerContext.GetSchema();
	for (int32 ArgIdx = 0; ArgIdx < PinNames.Num(); ++ArgIdx)
	{
		UEdGraphPin* ParameterPin = FindPin(PinNames[ArgIdx]);
		if (ParameterPin)
		{
			auto InputPin = CallNotifyFuncNode->CreatePin(EGPD_Input, ParameterPin->PinType, ParameterPin->PinName);
			bError &= CompilerContext.MovePinLinksToIntermediate(*ParameterPin, *InputPin).CanSafeConnect();
		}
	}
	SpawnNode->BreakAllNodeLinks();
}


void UEventsK2Node_NotifyEvent::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();
}

FText UEventsK2Node_NotifyEvent::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	return NSLOCTEXT("K2Node", "Notify_EVENT_Tag", "Notify Event");
}

FText UEventsK2Node_NotifyEvent::GetTooltipText() const
{
	return NSLOCTEXT("K2Node", "UEventsK2Node_NotifyEvent_ToolTip", "Selects an output that matches the input value");
}